"""initial schema

Revision ID: 0f21de344a88
Revises: 
Create Date: 2026-02-27 07:28:58.500079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f21de344a88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('accreditation', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_university_id'), 'university', ['id'], unique=False)
    op.create_index(op.f('ix_university_is_active'), 'university', ['is_active'], unique=False)
    op.create_index(op.f('ix_university_name'), 'university', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FRANCHISE', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('degree_type', sa.String(length=50), nullable=True),
    sa.Column('eligible_education', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'code', name='uq_course_university_code')
    )
    op.create_index(op.f('ix_course_id'), 'course', ['id'], unique=False)
    op.create_index(op.f('ix_course_is_active'), 'course', ['is_active'], unique=False)
    op.create_index(op.f('ix_course_name'), 'course', ['name'], unique=False)
    op.create_index(op.f('ix_course_university_id'), 'course', ['university_id'], unique=False)
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'name', name='uq_branch_course_name')
    )
    op.create_index(op.f('ix_branch_course_id'), 'branch', ['course_id'], unique=False)
    op.create_index(op.f('ix_branch_id'), 'branch', ['id'], unique=False)
    op.create_table('course_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('course_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_variant_branch_id'), 'course_variant', ['branch_id'], unique=False)
    op.create_index(op.f('ix_course_variant_course_id'), 'course_variant', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_variant_id'), 'course_variant', ['id'], unique=False)
    op.create_table('fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_variant_id', sa.Integer(), nullable=False),
    sa.Column('tuition_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('registration_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exam_fee_yearly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_first_year', sa.Numeric(precision=10, scale=2), sa.Computed('tuition_fee + registration_fee + exam_fee_yearly + other_fees', persisted=True), nullable=True),
    sa.Column('total_yearly', sa.Numeric(precision=10, scale=2), sa.Computed('tuition_fee + exam_fee_yearly + other_fees', persisted=True), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_variant_id'], ['course_variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_course_variant_id'), 'fee', ['course_variant_id'], unique=True)
    op.create_index(op.f('ix_fee_id'), 'fee', ['id'], unique=False)
    op.create_index(op.f('ix_fee_is_active'), 'fee', ['is_active'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=False),
    sa.Column('mother_name', sa.String(), nullable=False),
    sa.Column('degree_type', sa.String(length=20), nullable=True),
    sa.Column('previous_class', sa.String(), nullable=True),
    sa.Column('branch_specialization', sa.String(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('eighth_board', sa.String(length=50), nullable=True),
    sa.Column('eighth_board_other', sa.String(length=100), nullable=True),
    sa.Column('eighth_school', sa.String(length=255), nullable=True),
    sa.Column('eighth_passing_year', sa.String(length=4), nullable=True),
    sa.Column('eighth_percentage', sa.String(length=10), nullable=True),
    sa.Column('tenth_board', sa.String(length=50), nullable=True),
    sa.Column('tenth_board_other', sa.String(length=100), nullable=True),
    sa.Column('tenth_school', sa.String(length=255), nullable=True),
    sa.Column('tenth_passing_year', sa.String(length=4), nullable=True),
    sa.Column('tenth_percentage', sa.String(length=10), nullable=True),
    sa.Column('twelfth_board', sa.String(length=50), nullable=True),
    sa.Column('twelfth_board_other', sa.String(length=100), nullable=True),
    sa.Column('twelfth_school', sa.String(length=255), nullable=True),
    sa.Column('twelfth_passing_year', sa.String(length=4), nullable=True),
    sa.Column('twelfth_percentage', sa.String(length=10), nullable=True),
    sa.Column('grad_university', sa.String(length=255), nullable=True),
    sa.Column('grad_degree', sa.String(length=255), nullable=True),
    sa.Column('grad_passing_year', sa.String(length=4), nullable=True),
    sa.Column('grad_percentage', sa.String(length=10), nullable=True),
    sa.Column('grad_subject', sa.String(length=255), nullable=True),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('apaar_id', sa.String(length=50), nullable=True),
    sa.Column('session', sa.String(length=50), nullable=True),
    sa.Column('street_locality', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('aadhar_number', sa.String(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('course_variant_id', sa.Integer(), nullable=True),
    sa.Column('fee_id', sa.Integer(), nullable=True),
    sa.Column('passport_photo', sa.String(), nullable=True),
    sa.Column('aadhar_card_doc', sa.String(), nullable=True),
    sa.Column('doc_eighth', sa.String(), nullable=True),
    sa.Column('doc_tenth', sa.String(), nullable=True),
    sa.Column('doc_twelfth', sa.String(), nullable=True),
    sa.Column('doc_graduation', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'FAILED', name='admissionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_variant_id'], ['course_variant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fee_id'], ['fee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['franchise_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_branch_id'), 'student', ['branch_id'], unique=False)
    op.create_index(op.f('ix_student_course_id'), 'student', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_course_variant_id'), 'student', ['course_variant_id'], unique=False)
    op.create_index(op.f('ix_student_fee_id'), 'student', ['fee_id'], unique=False)
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=False)
    op.create_index(op.f('ix_student_university_id'), 'student', ['university_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_university_id'), table_name='student')
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_index(op.f('ix_student_fee_id'), table_name='student')
    op.drop_index(op.f('ix_student_course_variant_id'), table_name='student')
    op.drop_index(op.f('ix_student_course_id'), table_name='student')
    op.drop_index(op.f('ix_student_branch_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_fee_is_active'), table_name='fee')
    op.drop_index(op.f('ix_fee_id'), table_name='fee')
    op.drop_index(op.f('ix_fee_course_variant_id'), table_name='fee')
    op.drop_table('fee')
    op.drop_index(op.f('ix_course_variant_id'), table_name='course_variant')
    op.drop_index(op.f('ix_course_variant_course_id'), table_name='course_variant')
    op.drop_index(op.f('ix_course_variant_branch_id'), table_name='course_variant')
    op.drop_table('course_variant')
    op.drop_index(op.f('ix_branch_id'), table_name='branch')
    op.drop_index(op.f('ix_branch_course_id'), table_name='branch')
    op.drop_table('branch')
    op.drop_index(op.f('ix_course_university_id'), table_name='course')
    op.drop_index(op.f('ix_course_name'), table_name='course')
    op.drop_index(op.f('ix_course_is_active'), table_name='course')
    op.drop_index(op.f('ix_course_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_university_name'), table_name='university')
    op.drop_index(op.f('ix_university_is_active'), table_name='university')
    op.drop_index(op.f('ix_university_id'), table_name='university')
    op.drop_table('university')
    # ### end Alembic commands ###
