"""add education details commission and rename status

Revision ID: 35cf1078d536
Revises: c2616fad0655
Create Date: 2026-02-11 15:59:58.274652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35cf1078d536'
down_revision: Union[str, Sequence[str], None] = 'c2616fad0655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('degree_type', sa.String(length=20), nullable=True))
    op.add_column('student', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('student', sa.Column('tenth_board', sa.String(length=50), nullable=True))
    op.add_column('student', sa.Column('tenth_board_other', sa.String(length=100), nullable=True))
    op.add_column('student', sa.Column('tenth_school', sa.String(length=255), nullable=True))
    op.add_column('student', sa.Column('tenth_passing_year', sa.String(length=4), nullable=True))
    op.add_column('student', sa.Column('tenth_percentage', sa.String(length=10), nullable=True))
    op.add_column('student', sa.Column('twelfth_board', sa.String(length=50), nullable=True))
    op.add_column('student', sa.Column('twelfth_board_other', sa.String(length=100), nullable=True))
    op.add_column('student', sa.Column('twelfth_school', sa.String(length=255), nullable=True))
    op.add_column('student', sa.Column('twelfth_passing_year', sa.String(length=4), nullable=True))
    op.add_column('student', sa.Column('twelfth_percentage', sa.String(length=10), nullable=True))
    op.add_column('student', sa.Column('grad_university', sa.String(length=255), nullable=True))
    op.add_column('student', sa.Column('grad_degree', sa.String(length=255), nullable=True))
    op.add_column('student', sa.Column('grad_passing_year', sa.String(length=4), nullable=True))
    op.add_column('student', sa.Column('grad_percentage', sa.String(length=10), nullable=True))
    op.add_column('student', sa.Column('grad_subject', sa.String(length=255), nullable=True))
    op.add_column('student', sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('student', sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('student', 'previous_class',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'previous_class',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('student', 'commission_amount')
    op.drop_column('student', 'commission_percentage')
    op.drop_column('student', 'grad_subject')
    op.drop_column('student', 'grad_percentage')
    op.drop_column('student', 'grad_passing_year')
    op.drop_column('student', 'grad_degree')
    op.drop_column('student', 'grad_university')
    op.drop_column('student', 'twelfth_percentage')
    op.drop_column('student', 'twelfth_passing_year')
    op.drop_column('student', 'twelfth_school')
    op.drop_column('student', 'twelfth_board_other')
    op.drop_column('student', 'twelfth_board')
    op.drop_column('student', 'tenth_percentage')
    op.drop_column('student', 'tenth_passing_year')
    op.drop_column('student', 'tenth_school')
    op.drop_column('student', 'tenth_board_other')
    op.drop_column('student', 'tenth_board')
    op.drop_column('student', 'skills')
    op.drop_column('student', 'degree_type')
    # ### end Alembic commands ###
