"""add franchise detail fields

Revision ID: c2616fad0655
Revises: 972a6cb310f4
Create Date: 2026-02-11 15:42:47.712016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2616fad0655'
down_revision: Union[str, Sequence[str], None] = '972a6cb310f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user', sa.Column('gst_number', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('pan_number', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'pan_number')
    op.drop_column('user', 'gst_number')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
