"""Add apaar_id, session, district to stude

Revision ID: fcd052229707
Revises: a1b2c3d4e5f6
Create Date: 2026-02-16 13:42:55.868098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd052229707'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'eligible_education',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('fee', 'course_variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('student', sa.Column('apaar_id', sa.String(length=50), nullable=True))
    op.add_column('student', sa.Column('session', sa.String(length=50), nullable=True))
    op.add_column('student', sa.Column('district', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'district')
    op.drop_column('student', 'session')
    op.drop_column('student', 'apaar_id')
    op.alter_column('fee', 'course_variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course', 'eligible_education',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
